Fix build error
Received this when building:
ERROR in src/app/settings/settings.component.html(1,28): Property 'saving' does not exist on type 'SettingsComponent'.